### ISSUE TITLE
Include the Light Theme Too

### ISSUE THREAD

**Issue by BurnyBoi** [manjaro-pinephone/phosh#13]
I'm noticing on the latest updates, if I look at the available themes in the Tweaks app, they are "Adwaita", "Adwaita-dark", and "High Contrast", but both of the Adwaita themes are the dark theme. 

Can the regular light theme be added as an option as well? The dark theme doesn't work well when using the pinephone under sunlight and while the High Contrast works...it's kind of ugly by comparison.

**Comment by Strit** [comment]
This was caused by us setting the "prefer dark theme" option in gtk3 settings.

This setting is not applied anymore, so when you get the update to `pinephone-manjaro-tweaks` to 20211013, which is currently in both unstable and testing branch, the Adwaita theme is now the light theme and Adwaita-dark is the dark theme, which you can select in the Tweaks app.
